### ISSUE TITLE
v7.0.1 BUG

### ISSUE THREAD

**Issue by babakfp** [foray1010/ignore-sync#726]
```
rror: source `[]` not found before ignore pattern is found
    at file:///C:/Users/babak/OneDrive/Documents/GitHub/babakfp.ir/node_modules/.pnpm/ignore-sync@7.0.1/node_modules/ignore-sync/src/decodeIgnoreSyncFile.js:24:13
    at Array.reduce (<anonymous>)
    at decodeIgnoreSyncFile (file:///C:/Users/babak/OneDrive/Documents/GitHub/babakfp.ir/node_modules/.pnpm/ignore-sync@7.0.1/node_modules/ignore-sync/src/decodeIgnoreSyncFile.js:11:53)       
    at async processIgnoreSyncFile (file:///C:/Users/babak/OneDrive/Documents/GitHub/babakfp.ir/node_modules/.pnpm/ignore-sync@7.0.1/node_modules/ignore-sync/src/processIgnoreSyncFile.js:10:22)
    at async Promise.all (index 0)
    at async processDirectory (file:///C:/Users/babak/OneDrive/Documents/GitHub/babakfp.ir/node_modules/.pnpm/ignore-sync@7.0.1/node_modules/ignore-sync/src/processDirectory.js:43:5)
    at async startApp (file:///C:/Users/babak/OneDrive/Documents/GitHub/babakfp.ir/node_modules/.pnpm/ignore-sync@7.0.1/node_modules/ignore-sync/src/app.js:25:5)
```

This issue was resolved after switching to v7.0.0

**Comment by foray1010** [comment]
Can you provide a reproducible example?

**Comment by babakfp** [comment]
```
git clone https://github.com/babakfp/babakfp.ir
cd babakfp.ir
git checkout ca3b1375f64ff53c65662db92025f6805fc886da

pnpm i
pnpm ignore-sync
```

**Comment by foray1010** [comment]
That is a private repo, can u post the config file here?

**Comment by babakfp** [comment]
Ops!

Here's a proper reproduction: https://github.com/babakfp/foray1010.ignore-sync.issues.726

**Comment by foray1010** [comment]
It works fine on my side.

**Comment by babakfp** [comment]
https://github.com/foray1010/ignore-sync/assets/44144724/df22e6f6-550c-46b0-9464-15332919392f

```
NodeJS: v20.6.1
PNPM: 8.6.12
NPM: 9.8.1
Windows 11
```

**Comment by jpickwell** [comment]
I encountered this issue as well because ignore-sync recurses through the `.git` directory, and we have a branch named `gitignore-sync`, so ignore-sync sees `.git/logs/refs/heads/gitignore-sync` as a sync file.

ignore-sync should ignore the `.git` directory, but it doesn't.

```
ignore-sync: v8.0.0
```

**Comment by webbrain-dev** [comment]
Thanks for the report! I’ve opened [#991](https://github.com/foray1010/ignore-sync/pull/991) to fix this v7.0.1 bug by handling the empty/missing source case before processing ignore patterns, which should prevent the `source [] not found...` error and restore the behavior from v7.0.0.
